Parsowanie HTML
SiwyKrzysiek/weather-company pull request #1
Opened 2019-12-04 19:06 UTC by PawelOsinskii

2019-12-04 19:29 UTC, SiwyKrzysiek commented
Nie powinieneś używać `var`

2019-12-04 19:33 UTC, christopher-dabrowski requested changes
Praktycznie wszystko co się dało zrobić źle jest źle. Prawdopodobnie kod działa, ale nie jest dobrze napisany.

2019-12-04 19:33 UTC, SiwyKrzysiek commented on index.html
> +								<div id="opady" class="num">23<sup>o</sup>C</div>
Id jest po polsku

2019-12-04 19:33 UTC, SiwyKrzysiek commented on index.html
> +	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
Już mamy jQuery w projekcie

2019-12-04 19:33 UTC, SiwyKrzysiek commented on index.html
> +			document.getElementById('opady').innerHTML = weather_html;
Ustawianie `innderHTML`  jest bardzo wolne. Lepiej robić to obiektowo.

2019-12-04 19:33 UTC, SiwyKrzysiek commented on parsowanieJson.js
> +};
Ten kod nie jest nawet zaincludowany

2019-12-04 19:40 UTC, SiwyKrzysiek commented
Branch nie powinien się nazywać _pawel_

2019-12-05 07:13 UTC, SiwyKrzysiek commented on index.html
> +			var weather_html = (temp).toPrecision(2)+"<sup>o</sup>C";
Nie ma sensu budować całego tekstu w komórce. `<sup>o</sup>C` nigdy się nie zmienia. Lepiej zaktualizować samą liczbę.

2019-12-05 07:14 UTC, SiwyKrzysiek commented on index.html
> +		var data_url="https://api.openweathermap.org/data/2.5/weather?q=Warsaw,pl&APPID=7cad625ece0a657d34524777c3f14cfa";
Lokalizacja powinna być parametryzowana

2019-12-05 07:14 UTC, SiwyKrzysiek commented on index.html
> +	<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
Jeśli potrzebujesz nowszej wersji to możesz je zaktualizować

2019-12-05 07:16 UTC, SiwyKrzysiek commented on index.html
> +		// function to use jsonp to get weather information
Ten kod nie ma nic wspólnego z _jsonp_, ale to dobrze. **AJAX** jest zdecydowanie lepszy.

2019-12-05 07:30 UTC, SiwyKrzysiek commented on index.html
> +		getWeather(function (data) {
Nie rozumiem dlaczego tu znów jest `getWeather`

2019-12-05 07:32 UTC, SiwyKrzysiek commented
Wyświetlenie danych jest silnie powiązane z ich pobieraniem. Nie powinno tak być. Zamiast tego możesz zastosować wzorzec MVVM, albo jakiś prosty, wspólny model danych

2019-12-05 07:34 UTC, SiwyKrzysiek commented on index.html
> +			$.ajax({
Wydajniej będzie użyć **Fetch API** wbudowanego w przeglądarkę

2019-12-05 07:37 UTC, SiwyKrzysiek commented on index.html
> +		// function to use jsonp to get weather information
Jsonp jest traginczym i przestarzały rozwiązaniem. Jeśli nie musisz to go **nie używaj**! 
Zdecydowanie lepiej skorzystać z AJAX

2019-12-07 19:56 UTC, closed without merging